
ADD_FLASS := -lreadline
NAME_EXAM := exam
NAME_BUILD := myTerminal
all:
	gcc main.c -o $(NAME_EXAM).run $(ADD_FLASS)
	gcc terminal.c -o $(NAME_BUILD).run $(ADD_FLASS)

clean:
	rm -rf $(NAME_EXAM)
	rm -rf $(NAME_BUILD)